FRAMES = {
    "FRAME_CARRIER": None,
    "FRAME_CRUISER": None,
    "FRAME_DESTROYER": None,
    "FRAME_DRONE": {
        "symbol": "FRAME_DRONE",
        "name": "Drone",
        "description": "A small, unmanned spacecraft used for various tasks, such as surveillance, transportation, or combat.",
        "moduleSlots": 3,
        "mountingPoints": 2,
        "fuelCapacity": 80,
        "quality": 1,
        "requirements": {"power": 1, "crew": -4},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_EXPLORER": {
        "symbol": "FRAME_EXPLORER",
        "name": "Explorer",
        "description": "A large, long-range spacecraft designed for deep space exploration and scientific research.",
        "moduleSlots": 8,
        "mountingPoints": 2,
        "fuelCapacity": 800,
        "quality": 5,
        "requirements": {"power": 5, "crew": 30},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_FIGHTER": None,
    "FRAME_FRIGATE": {
        "symbol": "FRAME_FRIGATE",
        "name": "Frigate",
        "description": "A medium-sized, multi-purpose spacecraft, often used for combat, transport, or support operations.",
        "moduleSlots": 8,
        "mountingPoints": 5,
        "fuelCapacity": 400,
        "condition": 1,
        "integrity": 1,
        "requirements": {"power": 8, "crew": 25},
    },
    "FRAME_HEAVY_FREIGHTER": {
        "symbol": "FRAME_HEAVY_FREIGHTER",
        "name": "Heavy Freighter",
        "description": "A large, heavily-armed spacecraft used for cargo transport and other commercial operations in hostile environments.",
        "moduleSlots": 13,
        "mountingPoints": 3,
        "fuelCapacity": 2300,
        "quality": 7,
        "requirements": {"power": 10, "crew": 100},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_INTERCEPTOR": {
        "symbol": "FRAME_INTERCEPTOR",
        "name": "Interceptor",
        "description": "A small, agile spacecraft designed for high-speed, short-range combat missions.",
        "moduleSlots": 2,
        "mountingPoints": 2,
        "fuelCapacity": 160,
        "quality": 3,
        "requirements": {"power": 1, "crew": 5},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_LIGHT_FREIGHTER": {
        "symbol": "FRAME_LIGHT_FREIGHTER",
        "name": "Light Freighter",
        "description": "A small, versatile spacecraft used for cargo transport and other commercial operations.",
        "moduleSlots": 6,
        "mountingPoints": 1,
        "fuelCapacity": 600,
        "quality": 5,
        "requirements": {"power": 5, "crew": 40},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_MINER": {
        "symbol": "FRAME_MINER",
        "name": "Miner",
        "description": "A medium-sized spacecraft designed for mining operations and resource extraction.",
        "moduleSlots": 5,
        "mountingPoints": 3,
        "fuelCapacity": 300,
        "quality": 4,
        "requirements": {"power": 5, "crew": 15},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_PROBE": {
        "symbol": "FRAME_PROBE",
        "name": "Probe",
        "description": "A small, unmanned spacecraft used for exploration, reconnaissance, and scientific research.",
        "moduleSlots": 0,
        "mountingPoints": 0,
        "fuelCapacity": 0,
        "quality": 1,
        "requirements": {"power": 1, "crew": 0},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_RACER": None,
    "FRAME_SHUTTLE": {
        "symbol": "FRAME_SHUTTLE",
        "name": "Shuttle",
        "description": "A small, reusable spacecraft designed for short-range, low-speed travel between spacecraft or planetary surfaces.",
        "moduleSlots": 3,
        "mountingPoints": 1,
        "fuelCapacity": 300,
        "quality": 3,
        "requirements": {"power": 1, "crew": 10},
        "condition": 1,
        "integrity": 1,
    },
    "FRAME_TRANSPORT": None,
}
