GOODS = {
    "ADVANCED_CIRCUITRY": {
        "symbol": "ADVANCED_CIRCUITRY",
        "name": "Advanced Circuitry",
        "description": "Highly advanced and complex electronic components used in advanced technologies and systems.",
    },
    "AI_MAINFRAMES": {
        "symbol": "AI_MAINFRAMES",
        "name": "AI Mainframes",
        "description": "High-powered computer systems designed to support advanced artificial intelligence and machine learning algorithms.",
    },
    "ALUMINUM": {
        "symbol": "ALUMINUM",
        "name": "Aluminum",
        "description": "Aluminum is an essential component in the construction of ship hulls and other structural components.",
    },
    "ALUMINUM_ORE": {
        "symbol": "ALUMINUM_ORE",
        "name": "Aluminum Ore",
        "description": "A valuable ore used in the production of aluminum and other alloys. Aluminum ore is an essential component in the construction of ship hulls and other structural components.",
    },
    "AMMONIA_ICE": {
        "symbol": "AMMONIA_ICE",
        "name": "Ammonia Ice",
        "description": "A valuable substance used in the production of fertilizers and other chemical products.",
    },
    "AMMUNITION": {
        "symbol": "AMMUNITION",
        "name": "Ammunition",
        "description": "A wide range of ammunition for various firearms, including bullets, shells, and other projectiles.",
    },
    "ANTIMATTER": {
        "symbol": "ANTIMATTER",
        "name": "Antimatter",
        "description": "A highly valuable and dangerous substance used for advanced propulsion and weapons systems.",
    },
    "ASSAULT_RIFLES": {
        "symbol": "ASSAULT_RIFLES",
        "name": "Assault Rifles",
        "description": "High-powered rifles designed for rapid-fire combat and used by military forces and other trained personnel.",
    },
    "BIOCOMPOSITES": {
        "symbol": "BIOCOMPOSITES",
        "name": "Biocomposites",
        "description": "Composite materials made from natural and synthetic materials, used in various applications, such as medical implants and biodegradable packaging.",
    },
    "BOTANICAL_SPECIMENS": {
        "symbol": "BOTANICAL_SPECIMENS",
        "name": "Botanical Specimens",
        "description": "Samples of plants or other vegetation collected from various locations, often used for research or study.",
    },
    "CLOTHING": {
        "symbol": "CLOTHING",
        "name": "Clothing",
        "description": "A wide range of clothing and fashion items, including garments, accessories, and textiles.",
    },
    "COPPER": {
        "symbol": "COPPER",
        "name": "Copper",
        "description": "Copper is an essential component in the production of electronic components and wiring.",
    },
    "COPPER_ORE": {
        "symbol": "COPPER_ORE",
        "name": "Copper Ore",
        "description": "A valuable ore used in the production of copper and other alloys. Copper ore is an essential component in the production of electronic components and wiring.",
    },
    "CULTURAL_ARTIFACTS": None,
    "CYBER_IMPLANTS": {
        "symbol": "CYBER_IMPLANTS",
        "name": "Cyber Implants",
        "description": "Advanced implants that augment the human body with cybernetic enhancements, such as enhanced strength, speed, or intelligence.",
    },
    "DIAMONDS": {
        "symbol": "DIAMONDS",
        "name": "Diamonds",
        "description": "Rare and valuable crystals used in the production of high-end jewelry and other luxury goods.",
    },
    "DRUGS": {
        "symbol": "DRUGS",
        "name": "Pharmaceuticals",
        "description": "A wide range of drugs and other medical treatments used to treat various conditions and illnesses.",
    },
    "ELECTRONICS": {
        "symbol": "ELECTRONICS",
        "name": "Electronic Components",
        "description": "Advanced electronic components used in the construction of advanced technologies.",
    },
    "ENGINE_HYPER_DRIVE_I": {
        "symbol": "ENGINE_HYPER_DRIVE_I",
        "name": "Hyper Drive",
        "description": "An advanced propulsion system that uses exotic matter and gravitational fields to generate faster-than-light travel.",
    },
    "ENGINE_IMPULSE_DRIVE_I": {
        "symbol": "ENGINE_IMPULSE_DRIVE_I",
        "name": "Impulse Drive I",
        "description": "A basic low-energy propulsion system that generates thrust for interplanetary travel.",
    },
    "ENGINE_ION_DRIVE_I": {
        "symbol": "ENGINE_ION_DRIVE_I",
        "name": "Ion Drive I",
        "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration.",
    },
    "ENGINE_ION_DRIVE_II": {
        "symbol": "ENGINE_ION_DRIVE_II",
        "name": "Ion Drive II",
        "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration, with improved efficiency and performance.",
    },
    "EQUIPMENT": {
        "symbol": "EQUIPMENT",
        "name": "Equipment",
        "description": "Tools and equipment used in various industries and applications.",
    },
    "EXOTIC_MATTER": {
        "symbol": "EXOTIC_MATTER",
        "name": "Exotic Matter",
        "description": "A rare and highly valuable substance with unique properties, used in advanced technologies and weapons systems.",
    },
    "EXPLOSIVES": {
        "symbol": "EXPLOSIVES",
        "name": "Explosives",
        "description": "High-powered explosives used for mining, construction, and military operations.",
    },
    "FABRICS": {
        "symbol": "FABRICS",
        "name": "Synthetic Fabrics",
        "description": "High-tech fabrics used in the production of clothing and other products for everyday use.",
    },
    "FAB_MATS": {
        "symbol": "FAB_MATS",
        "name": "Fabrication Materials",
        "description": "Industrial materials essential in the construction of planetary habitats, space stations, and interstellar infrastructure.",
    },
    "FERTILIZERS": {
        "symbol": "FERTILIZERS",
        "name": "Fertilizers",
        "description": "Specialized chemicals used to enrich the soil and promote plant growth on newly-colonized planets.",
    },
    "FIREARMS": {
        "symbol": "FIREARMS",
        "name": "Galactic Arms",
        "description": "A wide range of weapons, including pistols, rifles, and shotguns, used for self-defense and military purposes.",
    },
    "FOOD": {
        "symbol": "FOOD",
        "name": "Galactic Cuisine",
        "description": "A diverse range of foods from different planets, including fresh produce, meats, and prepared meals.",
    },
    "FRAME_CARRIER": None,
    "FRAME_CRUISER": None,
    "FRAME_DESTROYER": None,
    "FRAME_DRONE": None,
    "FRAME_EXPLORER": None,
    "FRAME_FIGHTER": None,
    "FRAME_FRIGATE": None,
    "FRAME_HEAVY_FREIGHTER": None,
    "FRAME_INTERCEPTOR": None,
    "FRAME_LIGHT_FREIGHTER": None,
    "FRAME_MINER": None,
    "FRAME_PROBE": None,
    "FRAME_RACER": None,
    "FRAME_SHUTTLE": None,
    "FRAME_TRANSPORT": None,
    "FUEL": {
        "symbol": "FUEL",
        "name": "Fuel",
        "description": "High-energy fuel used in spacecraft propulsion systems to enable long-distance space travel.",
    },
    "GENE_THERAPEUTICS": {
        "symbol": "GENE_THERAPEUTICS",
        "name": "Gene Therapeutics",
        "description": "Medical treatments that use genetic engineering to treat or prevent diseases, or to enhance the human body.",
    },
    "GOLD": {
        "symbol": "GOLD",
        "name": "Gold",
        "description": "Gold is often used in the production of jewelry, coins, and other decorative items, as well as in the production of electronics and other high-tech applications.",
    },
    "GOLD_ORE": {
        "symbol": "GOLD_ORE",
        "name": "Gold Ore",
        "description": "A valuable ore used in the production of gold and other precious metals. Gold ore is often used in the production of jewelry, coins, and other decorative items, as well as in the production of electronics and other high-tech applications.",
    },
    "GRAVITON_EMITTERS": {
        "symbol": "GRAVITON_EMITTERS",
        "name": "Graviton Emitters",
        "description": "Advanced devices that generate and manipulate gravitons, used in advanced propulsion and weapons systems.",
    },
    "HOLOGRAPHICS": {
        "symbol": "HOLOGRAPHICS",
        "name": "Holographics",
        "description": "Advanced technology that allows for the creation of three-dimensional images using light and other electromagnetic fields.",
    },
    "HYDROCARBON": {
        "symbol": "HYDROCARBON",
        "name": "Hydrocarbons",
        "description": "A highly-valued substance used in the production of fuels, plastics, and other industrial products.",
    },
    "ICE_WATER": {
        "symbol": "ICE_WATER",
        "name": "Fresh Water",
        "description": "High-quality fresh water, essential for life support and hydroponic agriculture.",
    },
    "IRON": {
        "symbol": "IRON",
        "name": "Iron",
        "description": "A common and valuable metal often used in the construction of ship hulls and other structural components.",
    },
    "IRON_ORE": {
        "symbol": "IRON_ORE",
        "name": "Iron Ore",
        "description": "A common and valuable ore used in the production of steel and other alloys.",
    },
    "JEWELRY": {
        "symbol": "JEWELRY",
        "name": "Jewelry",
        "description": "Exquisite and valuable pieces of jewelry made from rare materials and precious gems.",
    },
    "LAB_INSTRUMENTS": {
        "symbol": "LAB_INSTRUMENTS",
        "name": "Lab Instruments",
        "description": "A wide range of scientific instruments and equipment used in research and development.",
    },
    "LASER_RIFLES": {
        "symbol": "LASER_RIFLES",
        "name": "Laser Rifles",
        "description": "Advanced weapons that use focused beams of light to deliver highly destructive energy to a target.",
    },
    "LIQUID_HYDROGEN": {
        "symbol": "LIQUID_HYDROGEN",
        "name": "Liquid Hydrogen",
        "description": "A highly efficient and lightweight fuel used in advanced propulsion systems.",
    },
    "LIQUID_NITROGEN": {
        "symbol": "LIQUID_NITROGEN",
        "name": "Liquid Nitrogen",
        "description": "A cryogenic fluid used in a variety of applications, including refrigeration and cryogenic freezing.",
    },
    "MACHINERY": {
        "symbol": "MACHINERY",
        "name": "Machinery",
        "description": "A variety of mechanical devices and equipment, used for industrial, construction, and other practical purposes.",
    },
    "MEDICINE": {
        "symbol": "MEDICINE",
        "name": "Medicine",
        "description": "Medical products, including drugs, treatments, and medical equipment.",
    },
    "MERITIUM": {
        "symbol": "MERITIUM",
        "name": "Meritium",
        "description": "A precious, metallic element used in the manufacture of luxury goods and high-tech equipment.",
    },
    "MERITIUM_ORE": {
        "symbol": "MERITIUM_ORE",
        "name": "Meritium Ore",
        "description": "A raw, unprocessed form of meritium, often found in deep space and on inhospitable planets.",
    },
    "MICROPROCESSORS": {
        "symbol": "MICROPROCESSORS",
        "name": "Microprocessors",
        "description": "High-powered and energy-efficient microprocessors used in advanced electronic devices and systems.",
    },
    "MICRO_FUSION_GENERATORS": {
        "symbol": "MICRO_FUSION_GENERATORS",
        "name": "Micro Fusion Generators",
        "description": "Compact fusion reactors that provide a clean, reliable, and virtually unlimited source of energy.",
    },
    "MILITARY_EQUIPMENT": {
        "symbol": "MILITARY_EQUIPMENT",
        "name": "Military Gear",
        "description": "A wide range of equipment used by military forces, including armor, vehicles, and advanced technologies.",
    },
    "MODULE_CARGO_HOLD_I": {
        "symbol": "MODULE_CARGO_HOLD_I",
        "name": "Cargo Hold",
        "description": "A module that increases a ship's cargo capacity.",
    },
    "MODULE_CARGO_HOLD_II": {
        "symbol": "MODULE_CARGO_HOLD_II",
        "name": "Expanded Cargo Hold",
        "description": "An expanded cargo hold module that provides more efficient storage space for a ship's cargo.",
    },
    "MODULE_CARGO_HOLD_III": {
        "symbol": "MODULE_CARGO_HOLD_III",
        "name": "Advanced Cargo Hold",
        "description": "A large cargo hold module with advanced robotics that provides more efficient storage space for a ship's cargo.",
    },
    "MODULE_CREW_QUARTERS_I": {
        "symbol": "MODULE_CREW_QUARTERS_I",
        "name": "Crew Quarters",
        "description": "A module that provides living space and amenities for the crew.",
    },
    "MODULE_ENVOY_QUARTERS_I": {
        "symbol": "MODULE_ENVOY_QUARTERS_I",
        "name": "Envoy Quarters",
        "description": "A module that provides living space and amenities for VIP passengers or diplomatic envoys.",
    },
    "MODULE_FUEL_REFINERY_I": None,
    "MODULE_GAS_PROCESSOR_I": {
        "symbol": "MODULE_GAS_PROCESSOR_I",
        "name": "Gas Processor",
        "description": "Filters and processes extracted gases into their component parts, filters out impurities, and containerizes them into raw storage units.",
    },
    "MODULE_JUMP_DRIVE_I": None,
    "MODULE_JUMP_DRIVE_II": None,
    "MODULE_JUMP_DRIVE_III": None,
    "MODULE_MICRO_REFINERY_I": {
        "symbol": "MODULE_MICRO_REFINERY_I",
        "name": "Micro Refinery",
        "description": "A small-scale refining module that processes raw materials into refined products.",
    },
    "MODULE_MINERAL_PROCESSOR_I": {
        "symbol": "MODULE_MINERAL_PROCESSOR_I",
        "name": "Mineral Processor",
        "description": "Crushes and processes extracted minerals and ores into their component parts, filters out impurities, and containerizes them into raw storage units.",
    },
    "MODULE_ORE_REFINERY_I": None,
    "MODULE_PASSENGER_CABIN_I": {
        "symbol": "MODULE_PASSENGER_CABIN_I",
        "name": "Passenger Cabin",
        "description": "A module that provides living space and amenities for passengers.",
    },
    "MODULE_SCIENCE_LAB_I": {
        "symbol": "MODULE_SCIENCE_LAB_I",
        "name": "Science Lab",
        "description": "A specialized module equipped with advanced instruments and equipment for scientific research and analysis.",
    },
    "MODULE_SHIELD_GENERATOR_I": {
        "symbol": "MODULE_SHIELD_GENERATOR_I",
        "name": "Shield Generator",
        "description": "A basic shield generator that provides protection against incoming weapons fire and other hazards.",
    },
    "MODULE_SHIELD_GENERATOR_II": {
        "symbol": "MODULE_SHIELD_GENERATOR_II",
        "name": "Advanced Shield Generator",
        "description": "An advanced shield generator that provides enhanced protection against incoming weapons fire and other hazards.",
    },
    "MODULE_WARP_DRIVE_I": None,
    "MODULE_WARP_DRIVE_II": None,
    "MODULE_WARP_DRIVE_III": None,
    "MOOD_REGULATORS": {
        "symbol": "MOOD_REGULATORS",
        "name": "Mood Regulators",
        "description": "Drugs or other medical treatments that are used to control or regulate mood and emotions.",
    },
    "MOUNT_GAS_SIPHON_I": {
        "symbol": "MOUNT_GAS_SIPHON_I",
        "name": "Gas Siphon I",
        "description": "A basic gas siphon that can extract gas from gas giants and other gas-rich bodies.",
    },
    "MOUNT_GAS_SIPHON_II": {
        "symbol": "MOUNT_GAS_SIPHON_II",
        "name": "Gas Siphon II",
        "description": "An advanced gas siphon that can extract gas from gas giants and other gas-rich bodies more efficiently and at a higher rate.",
    },
    "MOUNT_GAS_SIPHON_III": {
        "symbol": "MOUNT_GAS_SIPHON_III",
        "name": "Gas Siphon III",
        "description": "An advanced gas siphon that can extract gas from gas giants and other gas-rich bodies with even greater efficiency and at a higher rate.",
    },
    "MOUNT_LASER_CANNON_I": {
        "symbol": "MOUNT_LASER_CANNON_I",
        "name": "Laser Cannon",
        "description": "A basic laser weapon that fires concentrated beams of energy at high speed and accuracy.",
    },
    "MOUNT_MINING_LASER_I": {
        "symbol": "MOUNT_MINING_LASER_I",
        "name": "Mining Laser I",
        "description": "A basic mining laser that can be used to extract valuable minerals from asteroids and other space objects.",
    },
    "MOUNT_MINING_LASER_II": {
        "symbol": "MOUNT_MINING_LASER_II",
        "name": "Mining Laser II",
        "description": "An advanced mining laser that is more efficient and effective at extracting valuable minerals from asteroids and other space objects.",
    },
    "MOUNT_MINING_LASER_III": {
        "symbol": "MOUNT_MINING_LASER_III",
        "name": "Mining Laser III",
        "description": "An advanced mining laser that is even more efficient and effective at extracting valuable minerals from asteroids and other space objects.",
    },
    "MOUNT_MISSILE_LAUNCHER_I": {
        "symbol": "MOUNT_MISSILE_LAUNCHER_I",
        "name": "Missile Launcher",
        "description": "A basic missile launcher that fires guided missiles with a variety of warheads for different targets.",
    },
    "MOUNT_SENSOR_ARRAY_I": {
        "symbol": "MOUNT_SENSOR_ARRAY_I",
        "name": "Sensor Array I",
        "description": "A basic sensor array that improves a ship's ability to detect and track other objects in space.",
    },
    "MOUNT_SENSOR_ARRAY_II": {
        "symbol": "MOUNT_SENSOR_ARRAY_II",
        "name": "Sensor Array II",
        "description": "An advanced sensor array that improves a ship's ability to detect and track other objects in space with greater accuracy and range.",
    },
    "MOUNT_SENSOR_ARRAY_III": {
        "symbol": "MOUNT_SENSOR_ARRAY_III",
        "name": "Sensor Array III",
        "description": "An advanced sensor array that significantly improves a ship's ability to detect and track other objects in space with even greater accuracy and range.",
    },
    "MOUNT_SURVEYOR_I": {
        "symbol": "MOUNT_SURVEYOR_I",
        "name": "Surveyor I",
        "description": "A basic survey probe that can be used to gather information about a mineral deposit.",
    },
    "MOUNT_SURVEYOR_II": {
        "symbol": "MOUNT_SURVEYOR_II",
        "name": "Surveyor II",
        "description": "An advanced survey probe that can be used to gather information about a mineral deposit with greater accuracy.",
    },
    "MOUNT_SURVEYOR_III": {
        "symbol": "MOUNT_SURVEYOR_III",
        "name": "Surveyor III",
        "description": "An advanced survey probe that can be used to gather information about a mineral deposit with even greater accuracy.",
    },
    "MOUNT_TURRET_I": {
        "symbol": "MOUNT_TURRET_I",
        "name": "Rotary Cannon",
        "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
    },
    "NANOBOTS": {
        "symbol": "NANOBOTS",
        "name": "Nanobots",
        "description": "Tiny robots at the nanoscale, used in various applications, such as medical treatments, manufacturing, and environmental cleanup.",
    },
    "NEURAL_CHIPS": {
        "symbol": "NEURAL_CHIPS",
        "name": "Neural Chips",
        "description": "Microchips that are implanted in the brain to enhance cognitive abilities, such as memory, learning, and decision-making.",
    },
    "NOVEL_LIFEFORMS": {
        "symbol": "NOVEL_LIFEFORMS",
        "name": "Novel Lifeforms",
        "description": "New and unique species of plants or animals discovered on distant worlds, often of interest to scientists and collectors.",
    },
    "PLASTICS": {
        "symbol": "PLASTICS",
        "name": "Plastics",
        "description": "A wide range of plastic materials used in various applications, including packaging, construction, and manufacturing.",
    },
    "PLATINUM": {
        "symbol": "PLATINUM",
        "name": "Platinum",
        "description": "Platinum is often used in the production of catalysts and other industrial applications.",
    },
    "PLATINUM_ORE": {
        "symbol": "PLATINUM_ORE",
        "name": "Platinum Ore",
        "description": "A valuable ore used in the production of platinum and other precious metals. Platinum ore is often used in the production of catalysts and other industrial applications.",
    },
    "POLYNUCLEOTIDES": {
        "symbol": "POLYNUCLEOTIDES",
        "name": "Polynucleotides",
        "description": "A complex and highly valuable substance used in advanced medical treatments and biotechnology.",
    },
    "PRECIOUS_STONES": {
        "symbol": "PRECIOUS_STONES",
        "name": "Precious Stones",
        "description": "A collection of valuable gems and diamonds, often used in jewelry and other decorative objects.",
    },
    "QUANTUM_DRIVES": {
        "symbol": "QUANTUM_DRIVES",
        "name": "Quantum Drives",
        "description": "Advanced propulsion systems that use quantum mechanics to enable near-instantaneous travel over long distances.",
    },
    "QUANTUM_STABILIZERS": {
        "symbol": "QUANTUM_STABILIZERS",
        "name": "Quantum Stabilizers",
        "description": "Advanced devices that stabilize and control quantum fields, used in various spactime manipulation technologies.",
    },
    "QUARTZ_SAND": {
        "symbol": "QUARTZ_SAND",
        "name": "Quartz Sand",
        "description": "High-purity quartz sand used in the production of glass and ceramics.",
    },
    "REACTOR_ANTIMATTER_I": {
        "symbol": "REACTOR_ANTIMATTER_I",
        "name": "Antimatter Reactor I",
        "description": "A basic antimatter power reactor, used to generate electricity from the annihilation of matter and antimatter.",
    },
    "REACTOR_CHEMICAL_I": {
        "symbol": "REACTOR_CHEMICAL_I",
        "name": "Chemical Reactor I",
        "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
    },
    "REACTOR_FISSION_I": {
        "symbol": "REACTOR_FISSION_I",
        "name": "Fission Reactor I",
        "description": "A basic fission power reactor, used to generate electricity from nuclear fission reactions.",
    },
    "REACTOR_FUSION_I": {
        "symbol": "REACTOR_FUSION_I",
        "name": "Fusion Reactor I",
        "description": "A basic fusion power reactor, used to generate electricity from nuclear fusion reactions.",
    },
    "REACTOR_SOLAR_I": {
        "symbol": "REACTOR_SOLAR_I",
        "name": "Solar Reactor I",
        "description": "A basic solar power reactor, used to generate electricity from solar energy.",
    },
    "RELIC_TECH": {
        "symbol": "RELIC_TECH",
        "name": "Relic Tech",
        "description": "Advanced technology from ancient or extinct civilizations, often sought by collectors or researchers.",
    },
    "ROBOTIC_DRONES": {
        "symbol": "ROBOTIC_DRONES",
        "name": "Robotic Drones",
        "description": "Small, autonomous robots equipped with sensors and cameras, used for surveillance, exploration, and other tasks.",
    },
    "SHIP_COMMAND_FRIGATE": {
        "symbol": "SHIP_COMMAND_FRIGATE",
        "name": "Command Frigate",
        "description": "A medium-sized warship that is designed for command and control operations and can be fitted with a variety of weapons and other systems.",
    },
    "SHIP_EXPLORER": {
        "symbol": "SHIP_EXPLORER",
        "name": "Explorer",
        "description": "A large, long-range spacecraft designed for deep space exploration and scientific research.",
    },
    "SHIP_HEAVY_FREIGHTER": {
        "symbol": "SHIP_HEAVY_FREIGHTER",
        "name": "Heavy Freighter",
        "description": "The heavy freighter is a massive spacecraft designed for carrying large amounts of cargo across long distances. With its reinforced hull and advanced propulsion systems, the freighter is capable of navigating through harsh environments and hazardous conditions. It is equipped with a jump drive for faster-than-light travel, as well as a range of modules and mounts for handling a variety of cargo and defensive needs. The heavy freighter is a reliable and indispensable vessel for traders and haulers looking to transport goods and resources across the vast expanse of space.",
    },
    "SHIP_INTERCEPTOR": {
        "symbol": "SHIP_INTERCEPTOR",
        "name": "Interceptor",
        "description": "A small, agile spacecraft designed for high-speed, short-range combat missions.",
    },
    "SHIP_LIGHT_HAULER": {
        "symbol": "SHIP_LIGHT_HAULER",
        "name": "Light Hauler",
        "description": "A small, fast cargo ship that is designed for short-range transport of light loads.",
    },
    "SHIP_LIGHT_SHUTTLE": {
        "symbol": "SHIP_LIGHT_SHUTTLE",
        "name": "Light Shuttle",
        "description": "The light shuttle is a versatile spacecraft designed for exploration, diplomacy, and light cargo transport. With its compact size and agile maneuverability, the shuttle is capable of navigating through tight spaces and challenging environments.",
    },
    "SHIP_MINING_DRONE": {
        "symbol": "SHIP_MINING_DRONE",
        "name": "Mining Drone",
        "description": "A small, unmanned spacecraft that can be used for mining operations, such as extracting valuable minerals from asteroids.",
    },
    "SHIP_ORE_HOUND": {
        "symbol": "SHIP_ORE_HOUND",
        "name": "Ore Hound",
        "description": "The Ore Hound is a specialized mining ship designed for extracting valuable ores and minerals from asteroids and other celestial bodies. With its advanced mining lasers and reinforced hull, the Ore Hound is capable of excavating large amounts of ore and minerals from even the toughest asteroids. It is equipped with a range of modules and mounts for handling a variety of mining and defensive needs, and is an essential vessel for miners and traders looking to profit from the rich resources of the galaxy.",
    },
    "SHIP_PARTS": {
        "symbol": "SHIP_PARTS",
        "name": "Ship Parts",
        "description": "Various components and hardware required for spacecraft maintenance, upgrades, and construction.",
    },
    "SHIP_PLATING": {
        "symbol": "SHIP_PLATING",
        "name": "Ship Plating",
        "description": "High-quality metal plating used in the construction of ship hulls and other structural components.",
    },
    "SHIP_PROBE": {
        "symbol": "SHIP_PROBE",
        "name": "Probe Satellite",
        "description": "A small, unmanned spacecraft that can be launched into orbit to gather data and perform basic tasks.",
    },
    "SHIP_REFINING_FREIGHTER": {
        "symbol": "SHIP_REFINING_FREIGHTER",
        "name": "Refining Freighter",
        "description": "A large cargo ship designed specifically for refining raw materials. Equipped with a powerful reactor and space for large modules, the refining freighter is a versatile and convenient tool for industrial operations in remote or difficult-to-reach locations.",
    },
    "SHIP_SALVAGE": None,
    "SHIP_SIPHON_DRONE": {
        "symbol": "SHIP_SIPHON_DRONE",
        "name": "Mining Drone",
        "description": "A small, unmanned spacecraft that can be used for siphoning operations, such as extracting valuable gases from gas giants.",
    },
    "SHIP_SURVEYOR": {
        "symbol": "SHIP_SURVEYOR",
        "name": "Surveyor Craft",
        "description": "A specialized spacecraft equipped with surveying mounts, designed for detailed surveying of celestial bodies, resource identification, and scientific research.",
    },
    "SILICON_CRYSTALS": {
        "symbol": "SILICON_CRYSTALS",
        "name": "Silicon Crystals",
        "description": "High-quality silicon crystals used in the production of advanced electronic components and solar panels.",
    },
    "SILVER": {
        "symbol": "SILVER",
        "name": "Silver",
        "description": "A shiny, metallic element used in the production of coins, jewelry, and other high-value items.",
    },
    "SILVER_ORE": {
        "symbol": "SILVER_ORE",
        "name": "Silver Ore",
        "description": "A raw, unprocessed form of silver, often found in mines and underground deposits on planets and moons.",
    },
    "SUPERGRAINS": {
        "symbol": "SUPERGRAINS",
        "name": "Supergrains",
        "description": "Genetically modified grains with enhanced nutritional value, yield, and resistance to pests and diseases.",
    },
    "URANITE": {
        "symbol": "URANITE",
        "name": "Uranite",
        "description": "A rare, radioactive mineral used in the production of advanced technologies and weaponry.",
    },
    "URANITE_ORE": {
        "symbol": "URANITE_ORE",
        "name": "Uranite Ore",
        "description": "A raw, unprocessed form of uranite, often found in asteroid belts and other remote locations.",
    },
    "VIRAL_AGENTS": {
        "symbol": "VIRAL_AGENTS",
        "name": "Viral Agents",
        "description": "Viruses or other biological agents that are used for various purposes, such as medical treatments, weapons, or environmental remediation.",
    },
}
