REACTORS = {
    "REACTOR_ANTIMATTER_I": None,
    "REACTOR_CHEMICAL_I": {
        "symbol": "REACTOR_CHEMICAL_I",
        "name": "Chemical Reactor I",
        "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
        "powerOutput": 15,
        "quality": 3,
        "requirements": {"crew": 3},
        "condition": 1,
        "integrity": 1,
    },
    "REACTOR_FISSION_I": {
        "symbol": "REACTOR_FISSION_I",
        "name": "Fission Reactor I",
        "description": "A basic fission power reactor, used to generate electricity from nuclear fission reactions.",
        "powerOutput": 31,
        "quality": 5,
        "requirements": {"crew": 8},
        "condition": 1,
        "integrity": 1,
    },
    "REACTOR_FUSION_I": {
        "symbol": "REACTOR_FUSION_I",
        "name": "Fusion Reactor I",
        "description": "A basic fusion power reactor, used to generate electricity from nuclear fusion reactions.",
        "powerOutput": 40,
        "quality": 7,
        "requirements": {"crew": 12},
        "condition": 1,
        "integrity": 1,
    },
    "REACTOR_SOLAR_I": {
        "symbol": "REACTOR_SOLAR_I",
        "name": "Solar Reactor I",
        "description": "A basic solar power reactor, used to generate electricity from solar energy.",
        "powerOutput": 3,
        "quality": 1,
        "requirements": {"crew": 0},
        "condition": 1,
        "integrity": 1,
    },
}
