SHIPS = {
    "SHIP_COMMAND_FRIGATE": {
        "type": "SHIP_COMMAND_FRIGATE",
        "name": "Command Frigate",
        "description": "A medium-sized warship that is designed for command and control operations and can be fitted with a variety of weapons and other systems.",
        "purchasePrice": None,
        "frame": {
            "symbol": "FRAME_FRIGATE",
            "name": "Frigate",
            "description": "A medium-sized, multi-purpose spacecraft, often used for combat, transport, or support operations.",
            "moduleSlots": 8,
            "mountingPoints": 5,
            "fuelCapacity": 400,
            "quality": None,
            "requirements": {"power": 8, "crew": 25},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_FISSION_I",
            "name": "Fission Reactor I",
            "description": "A basic fission power reactor, used to generate electricity from nuclear fission reactions.",
            "powerOutput": 31,
            "quality": 5,
            "requirements": {"crew": 8},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_ION_DRIVE_II",
            "name": "Ion Drive II",
            "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration, with improved efficiency and performance.",
            "speed": 30,
            "quality": 4,
            "requirements": {"power": 6, "crew": 8},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_II",
                "name": "Expanded Cargo Hold",
                "description": "An expanded cargo hold module that provides more efficient storage space for a ship's cargo.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 2, "slots": 2},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_MINERAL_PROCESSOR_I",
                "name": "Mineral Processor",
                "description": "Crushes and processes extracted minerals and ores into their component parts, filters out impurities, and containerizes them into raw storage units.",
                "requirements": {"crew": 0, "power": 1, "slots": 2},
            },
            {
                "symbol": "MODULE_GAS_PROCESSOR_I",
                "name": "Gas Processor",
                "description": "Filters and processes extracted gases into their component parts, filters out impurities, and containerizes them into raw storage units.",
                "requirements": {"crew": 0, "power": 1, "slots": 2},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_SENSOR_ARRAY_II",
                "name": "Sensor Array II",
                "description": "An advanced sensor array that improves a ship's ability to detect and track other objects in space with greater accuracy and range.",
                "strength": 4,
                "requirements": {"crew": 2, "power": 2},
            },
            {
                "symbol": "MOUNT_GAS_SIPHON_II",
                "name": "Gas Siphon II",
                "description": "An advanced gas siphon that can extract gas from gas giants and other gas-rich bodies more efficiently and at a higher rate.",
                "strength": 20,
                "requirements": {"crew": 2, "power": 2},
            },
            {
                "symbol": "MOUNT_MINING_LASER_II",
                "name": "Mining Laser II",
                "description": "An advanced mining laser that is more efficient and effective at extracting valuable minerals from asteroids and other space objects.",
                "strength": 5,
                "requirements": {"crew": 2, "power": 2},
            },
            {
                "symbol": "MOUNT_SURVEYOR_II",
                "name": "Surveyor II",
                "description": "An advanced survey probe that can be used to gather information about a mineral deposit with greater accuracy.",
                "strength": 2,
                "deposits": [
                    "QUARTZ_SAND",
                    "SILICON_CRYSTALS",
                    "PRECIOUS_STONES",
                    "ICE_WATER",
                    "AMMONIA_ICE",
                    "IRON_ORE",
                    "COPPER_ORE",
                    "SILVER_ORE",
                    "ALUMINUM_ORE",
                    "GOLD_ORE",
                    "PLATINUM_ORE",
                    "DIAMONDS",
                    "URANITE_ORE",
                ],
                "requirements": {"crew": 4, "power": 3},
            },
        ],
        "crew": {"required": 57, "capacity": 80},
    },
    "SHIP_EXPLORER": {
        "type": "SHIP_EXPLORER",
        "name": "Explorer",
        "description": "A large, long-range spacecraft designed for deep space exploration and scientific research.",
        "purchasePrice": 841358,
        "frame": {
            "symbol": "FRAME_EXPLORER",
            "name": "Explorer",
            "description": "A large, long-range spacecraft designed for deep space exploration and scientific research.",
            "moduleSlots": 8,
            "mountingPoints": 2,
            "fuelCapacity": 800,
            "quality": 5,
            "requirements": {"power": 5, "crew": 30},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_FUSION_I",
            "name": "Fusion Reactor I",
            "description": "A basic fusion power reactor, used to generate electricity from nuclear fusion reactions.",
            "powerOutput": 40,
            "quality": 7,
            "requirements": {"crew": 12},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_ION_DRIVE_II",
            "name": "Ion Drive II",
            "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration, with improved efficiency and performance.",
            "speed": 30,
            "quality": 4,
            "requirements": {"power": 6, "crew": 8},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_II",
                "name": "Expanded Cargo Hold",
                "description": "An expanded cargo hold module that provides more efficient storage space for a ship's cargo.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 2, "slots": 2},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_WARP_DRIVE_I",
                "name": "Warp Drive I",
                "description": "A basic warp drive that allows for short-range interstellar travel.",
                "range": 2000,
                "requirements": {"crew": 2, "power": 3, "slots": 1},
            },
            {
                "symbol": "MODULE_GAS_PROCESSOR_I",
                "name": "Gas Processor",
                "description": "Filters and processes extracted gases into their component parts, filters out impurities, and containerizes them into raw storage units.",
                "requirements": {"crew": 0, "power": 1, "slots": 2},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_SENSOR_ARRAY_II",
                "name": "Sensor Array II",
                "description": "An advanced sensor array that improves a ship's ability to detect and track other objects in space with greater accuracy and range.",
                "strength": 4,
                "requirements": {"crew": 2, "power": 2},
            },
            {
                "symbol": "MOUNT_GAS_SIPHON_II",
                "name": "Gas Siphon II",
                "description": "An advanced gas siphon that can extract gas from gas giants and other gas-rich bodies more efficiently and at a higher rate.",
                "strength": 20,
                "requirements": {"crew": 2, "power": 2},
            },
        ],
        "crew": {"required": 62, "capacity": 80},
    },
    "SHIP_HEAVY_FREIGHTER": {
        "type": "SHIP_HEAVY_FREIGHTER",
        "name": "Heavy Freighter",
        "description": "The heavy freighter is a massive spacecraft designed for carrying large amounts of cargo across long distances. With its reinforced hull and advanced propulsion systems, the freighter is capable of navigating through harsh environments and hazardous conditions. It is equipped with a jump drive for faster-than-light travel, as well as a range of modules and mounts for handling a variety of cargo and defensive needs. The heavy freighter is a reliable and indispensable vessel for traders and haulers looking to transport goods and resources across the vast expanse of space.",
        "purchasePrice": None,
        "frame": {
            "symbol": "FRAME_HEAVY_FREIGHTER",
            "name": "Heavy Freighter",
            "description": "A large, heavily-armed spacecraft used for cargo transport and other commercial operations in hostile environments.",
            "moduleSlots": 13,
            "mountingPoints": 3,
            "fuelCapacity": 2300,
            "quality": 7,
            "requirements": {"power": 10, "crew": 100},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_FUSION_I",
            "name": "Fusion Reactor I",
            "description": "A basic fusion power reactor, used to generate electricity from nuclear fusion reactions.",
            "powerOutput": 40,
            "quality": 7,
            "requirements": {"crew": 12},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_ION_DRIVE_II",
            "name": "Ion Drive II",
            "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration, with improved efficiency and performance.",
            "speed": 30,
            "quality": 4,
            "requirements": {"power": 6, "crew": 8},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_III",
                "capacity": 75,
                "name": "Advanced Cargo Hold",
                "description": "A large cargo hold module with advanced robotics that provides more efficient storage space for a ship's cargo.",
                "requirements": {"power": 4, "crew": 6, "slots": 3},
            },
            {
                "symbol": "MODULE_CARGO_HOLD_III",
                "capacity": 75,
                "name": "Advanced Cargo Hold",
                "description": "A large cargo hold module with advanced robotics that provides more efficient storage space for a ship's cargo.",
                "requirements": {"power": 4, "crew": 6, "slots": 3},
            },
            {
                "symbol": "MODULE_CARGO_HOLD_III",
                "capacity": 75,
                "name": "Advanced Cargo Hold",
                "description": "A large cargo hold module with advanced robotics that provides more efficient storage space for a ship's cargo.",
                "requirements": {"power": 4, "crew": 6, "slots": 3},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "capacity": 40,
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "requirements": {"power": 1, "crew": 2, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "capacity": 40,
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "requirements": {"power": 1, "crew": 2, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "capacity": 40,
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "requirements": {"power": 1, "crew": 2, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "capacity": 40,
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "requirements": {"power": 1, "crew": 2, "slots": 1},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            },
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            },
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            },
        ],
        "crew": {"required": 149, "capacity": 160},
    },
    "SHIP_INTERCEPTOR": {
        "type": "SHIP_INTERCEPTOR",
        "name": "Interceptor",
        "description": "A small, agile spacecraft designed for high-speed, short-range combat missions.",
        "purchasePrice": 50224,
        "frame": {
            "symbol": "FRAME_INTERCEPTOR",
            "name": "Interceptor",
            "description": "A small, agile spacecraft designed for high-speed, short-range combat missions.",
            "moduleSlots": 2,
            "mountingPoints": 2,
            "fuelCapacity": 160,
            "quality": 3,
            "requirements": {"power": 1, "crew": 5},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_CHEMICAL_I",
            "name": "Chemical Reactor I",
            "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
            "powerOutput": 15,
            "quality": 3,
            "requirements": {"crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_ION_DRIVE_I",
            "name": "Ion Drive I",
            "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration.",
            "speed": 10,
            "quality": 3,
            "requirements": {"power": 3, "crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            }
        ],
        "mounts": [
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            },
            {
                "symbol": "MOUNT_MISSILE_LAUNCHER_I",
                "name": "Missile Launcher",
                "description": "A basic missile launcher that fires guided missiles with a variety of warheads for different targets.",
                "requirements": {"power": 1, "crew": 2},
            },
        ],
        "crew": {"required": 16, "capacity": 40},
    },
    "SHIP_LIGHT_HAULER": {
        "type": "SHIP_LIGHT_HAULER",
        "name": "Light Hauler",
        "description": "A small, fast cargo ship that is designed for short-range transport of light loads.",
        "purchasePrice": 392923,
        "frame": {
            "symbol": "FRAME_LIGHT_FREIGHTER",
            "name": "Light Freighter",
            "description": "A small, versatile spacecraft used for cargo transport and other commercial operations.",
            "moduleSlots": 6,
            "mountingPoints": 1,
            "fuelCapacity": 600,
            "quality": 5,
            "requirements": {"power": 5, "crew": 40},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_CHEMICAL_I",
            "name": "Chemical Reactor I",
            "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
            "powerOutput": 15,
            "quality": 3,
            "requirements": {"crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_ION_DRIVE_I",
            "name": "Ion Drive I",
            "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration.",
            "speed": 10,
            "quality": 3,
            "requirements": {"power": 3, "crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_II",
                "name": "Expanded Cargo Hold",
                "description": "An expanded cargo hold module that provides more efficient storage space for a ship's cargo.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 2, "slots": 2},
            },
            {
                "symbol": "MODULE_CARGO_HOLD_II",
                "name": "Expanded Cargo Hold",
                "description": "An expanded cargo hold module that provides more efficient storage space for a ship's cargo.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 2, "slots": 2},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            }
        ],
        "crew": {"required": 55, "capacity": 80},
    },
    "SHIP_LIGHT_SHUTTLE": {
        "type": "SHIP_LIGHT_SHUTTLE",
        "name": "Light Shuttle",
        "description": "The light shuttle is a versatile spacecraft designed for exploration, diplomacy, and light cargo transport. With its compact size and agile maneuverability, the shuttle is capable of navigating through tight spaces and challenging environments.",
        "purchasePrice": 99626,
        "frame": {
            "symbol": "FRAME_SHUTTLE",
            "name": "Shuttle",
            "description": "A small, reusable spacecraft designed for short-range, low-speed travel between spacecraft or planetary surfaces.",
            "moduleSlots": 3,
            "mountingPoints": 1,
            "fuelCapacity": 300,
            "quality": 3,
            "requirements": {"power": 1, "crew": 10},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_CHEMICAL_I",
            "name": "Chemical Reactor I",
            "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
            "powerOutput": 15,
            "quality": 3,
            "requirements": {"crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_IMPULSE_DRIVE_I",
            "name": "Impulse Drive I",
            "description": "A basic low-energy propulsion system that generates thrust for interplanetary travel.",
            "speed": 3,
            "quality": 1,
            "requirements": {"power": 1, "crew": 0},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_II",
                "name": "Expanded Cargo Hold",
                "description": "An expanded cargo hold module that provides more efficient storage space for a ship's cargo.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 2, "slots": 2},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            }
        ],
        "crew": {"required": 18, "capacity": 40},
    },
    "SHIP_MINING_DRONE": {
        "type": "SHIP_MINING_DRONE",
        "name": "Mining Drone",
        "description": "A small, unmanned spacecraft that can be used for mining operations, such as extracting valuable minerals from asteroids.",
        "purchasePrice": 51808,
        "frame": {
            "symbol": "FRAME_DRONE",
            "name": "Drone",
            "description": "A small, unmanned spacecraft used for various tasks, such as surveillance, transportation, or combat.",
            "moduleSlots": 3,
            "mountingPoints": 2,
            "fuelCapacity": 80,
            "quality": 1,
            "requirements": {"power": 1, "crew": -4},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_CHEMICAL_I",
            "name": "Chemical Reactor I",
            "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
            "powerOutput": 15,
            "quality": 3,
            "requirements": {"crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_IMPULSE_DRIVE_I",
            "name": "Impulse Drive I",
            "description": "A basic low-energy propulsion system that generates thrust for interplanetary travel.",
            "speed": 3,
            "quality": 1,
            "requirements": {"power": 1, "crew": 0},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_I",
                "name": "Cargo Hold",
                "description": "A module that increases a ship's cargo capacity.",
                "capacity": 15,
                "requirements": {"crew": 0, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_MINERAL_PROCESSOR_I",
                "name": "Mineral Processor",
                "description": "Crushes and processes extracted minerals and ores into their component parts, filters out impurities, and containerizes them into raw storage units.",
                "requirements": {"crew": 0, "power": 1, "slots": 2},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_MINING_LASER_I",
                "name": "Mining Laser I",
                "description": "A basic mining laser that can be used to extract valuable minerals from asteroids and other space objects.",
                "strength": 3,
                "requirements": {"crew": 1, "power": 1},
            }
        ],
        "crew": {"required": 0, "capacity": 0},
    },
    "SHIP_ORE_HOUND": {
        "type": "SHIP_ORE_HOUND",
        "name": "Ore Hound",
        "description": "The Ore Hound is a specialized mining ship designed for extracting valuable ores and minerals from asteroids and other celestial bodies. With its advanced mining lasers and reinforced hull, the Ore Hound is capable of excavating large amounts of ore and minerals from even the toughest asteroids. It is equipped with a range of modules and mounts for handling a variety of mining and defensive needs, and is an essential vessel for miners and traders looking to profit from the rich resources of the galaxy.",
        "purchasePrice": 262229,
        "frame": {
            "symbol": "FRAME_MINER",
            "name": "Miner",
            "description": "A medium-sized spacecraft designed for mining operations and resource extraction.",
            "moduleSlots": 5,
            "mountingPoints": 3,
            "fuelCapacity": 300,
            "quality": 4,
            "requirements": {"power": 5, "crew": 15},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_FISSION_I",
            "name": "Fission Reactor I",
            "description": "A basic fission power reactor, used to generate electricity from nuclear fission reactions.",
            "powerOutput": 31,
            "quality": 5,
            "requirements": {"crew": 8},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_ION_DRIVE_I",
            "name": "Ion Drive I",
            "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration.",
            "speed": 10,
            "quality": 3,
            "requirements": {"power": 3, "crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_II",
                "name": "Expanded Cargo Hold",
                "description": "An expanded cargo hold module that provides more efficient storage space for a ship's cargo.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 2, "slots": 2},
            },
            {
                "symbol": "MODULE_MINERAL_PROCESSOR_I",
                "name": "Mineral Processor",
                "description": "Crushes and processes extracted minerals and ores into their component parts, filters out impurities, and containerizes them into raw storage units.",
                "requirements": {"crew": 0, "power": 1, "slots": 2},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_MINING_LASER_II",
                "name": "Mining Laser II",
                "description": "An advanced mining laser that is more efficient and effective at extracting valuable minerals from asteroids and other space objects.",
                "strength": 5,
                "requirements": {"crew": 2, "power": 2},
            },
            {
                "symbol": "MOUNT_SURVEYOR_I",
                "name": "Surveyor I",
                "description": "A basic survey probe that can be used to gather information about a mineral deposit.",
                "strength": 1,
                "deposits": [
                    "QUARTZ_SAND",
                    "SILICON_CRYSTALS",
                    "PRECIOUS_STONES",
                    "ICE_WATER",
                    "AMMONIA_ICE",
                    "IRON_ORE",
                    "COPPER_ORE",
                    "SILVER_ORE",
                    "ALUMINUM_ORE",
                    "GOLD_ORE",
                    "PLATINUM_ORE",
                ],
                "requirements": {"crew": 1, "power": 1},
            },
        ],
        "crew": {"required": 33, "capacity": 40},
    },
    "SHIP_PROBE": {
        "type": "SHIP_PROBE",
        "name": "Probe Satellite",
        "description": "A small, unmanned spacecraft that can be launched into orbit to gather data and perform basic tasks.",
        "purchasePrice": 28083,
        "frame": {
            "symbol": "FRAME_PROBE",
            "name": "Probe",
            "description": "A small, unmanned spacecraft used for exploration, reconnaissance, and scientific research.",
            "moduleSlots": 0,
            "mountingPoints": 0,
            "fuelCapacity": 0,
            "quality": 1,
            "requirements": {"power": 1, "crew": 0},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_SOLAR_I",
            "name": "Solar Reactor I",
            "description": "A basic solar power reactor, used to generate electricity from solar energy.",
            "powerOutput": 3,
            "quality": 1,
            "requirements": {"crew": 0},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_IMPULSE_DRIVE_I",
            "name": "Impulse Drive I",
            "description": "A basic low-energy propulsion system that generates thrust for interplanetary travel.",
            "speed": 3,
            "quality": 1,
            "requirements": {"power": 1, "crew": 0},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [],
        "mounts": [],
        "crew": {"required": 0, "capacity": 0},
    },
    "SHIP_REFINING_FREIGHTER": {
        "type": "SHIP_REFINING_FREIGHTER",
        "name": "Refining Freighter",
        "description": "A large cargo ship designed specifically for refining raw materials. Equipped with a powerful reactor and space for large modules, the refining freighter is a versatile and convenient tool for industrial operations in remote or difficult-to-reach locations.",
        "purchasePrice": 2093358,
        "frame": {
            "symbol": "FRAME_HEAVY_FREIGHTER",
            "name": "Heavy Freighter",
            "description": "A large, heavily-armed spacecraft used for cargo transport and other commercial operations in hostile environments.",
            "moduleSlots": 13,
            "mountingPoints": 3,
            "fuelCapacity": 2300,
            "quality": 7,
            "requirements": {"power": 10, "crew": 100},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_FUSION_I",
            "name": "Fusion Reactor I",
            "description": "A basic fusion power reactor, used to generate electricity from nuclear fusion reactions.",
            "powerOutput": 40,
            "quality": 7,
            "requirements": {"crew": 12},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_ION_DRIVE_II",
            "name": "Ion Drive II",
            "description": "An advanced propulsion system that uses ionized particles to generate high-speed, low-thrust acceleration, with improved efficiency and performance.",
            "speed": 30,
            "quality": 4,
            "requirements": {"power": 6, "crew": 8},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_III",
                "name": "Advanced Cargo Hold",
                "description": "A large cargo hold module with advanced robotics that provides more efficient storage space for a ship's cargo.",
                "capacity": 75,
                "requirements": {"crew": 6, "power": 4, "slots": 3},
            },
            {
                "symbol": "MODULE_CARGO_HOLD_III",
                "name": "Advanced Cargo Hold",
                "description": "A large cargo hold module with advanced robotics that provides more efficient storage space for a ship's cargo.",
                "capacity": 75,
                "requirements": {"crew": 6, "power": 4, "slots": 3},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_CREW_QUARTERS_I",
                "name": "Crew Quarters",
                "description": "A module that provides living space and amenities for the crew.",
                "capacity": 40,
                "requirements": {"crew": 2, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_ORE_REFINERY_I",
                "name": "Ore Refinery",
                "description": "A specialized module that can refine raw ores into usable metals and other materials.",
                "production": [
                    "IRON",
                    "COPPER",
                    "SILVER",
                    "GOLD",
                    "ALUMINUM",
                    "PLATINUM",
                    "URANITE",
                    "MERITIUM",
                ],
                "requirements": {"crew": 15, "power": 9, "slots": 3},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            },
            {
                "symbol": "MOUNT_TURRET_I",
                "name": "Rotary Cannon",
                "description": "A rotary cannon is a type of mounted turret that is designed to fire a high volume of rounds in rapid succession.",
                "requirements": {"power": 1, "crew": 1},
            },
            {
                "symbol": "MOUNT_MISSILE_LAUNCHER_I",
                "name": "Missile Launcher",
                "description": "A basic missile launcher that fires guided missiles with a variety of warheads for different targets.",
                "requirements": {"power": 1, "crew": 2},
            },
        ],
        "crew": {"required": 159, "capacity": 160},
    },
    "SHIP_SIPHON_DRONE": {
        "type": "SHIP_SIPHON_DRONE",
        "name": "Mining Drone",
        "description": "A small, unmanned spacecraft that can be used for siphoning operations, such as extracting valuable gases from gas giants.",
        "purchasePrice": 50240,
        "frame": {
            "symbol": "FRAME_DRONE",
            "name": "Drone",
            "description": "A small, unmanned spacecraft used for various tasks, such as surveillance, transportation, or combat.",
            "moduleSlots": 3,
            "mountingPoints": 2,
            "fuelCapacity": 80,
            "quality": 1,
            "requirements": {"power": 1, "crew": -4},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_CHEMICAL_I",
            "name": "Chemical Reactor I",
            "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
            "powerOutput": 15,
            "quality": 3,
            "requirements": {"crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_IMPULSE_DRIVE_I",
            "name": "Impulse Drive I",
            "description": "A basic low-energy propulsion system that generates thrust for interplanetary travel.",
            "speed": 3,
            "quality": 1,
            "requirements": {"power": 1, "crew": 0},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [
            {
                "symbol": "MODULE_CARGO_HOLD_I",
                "name": "Cargo Hold",
                "description": "A module that increases a ship's cargo capacity.",
                "capacity": 15,
                "requirements": {"crew": 0, "power": 1, "slots": 1},
            },
            {
                "symbol": "MODULE_GAS_PROCESSOR_I",
                "name": "Gas Processor",
                "description": "Filters and processes extracted gases into their component parts, filters out impurities, and containerizes them into raw storage units.",
                "requirements": {"crew": 0, "power": 1, "slots": 2},
            },
        ],
        "mounts": [
            {
                "symbol": "MOUNT_GAS_SIPHON_I",
                "name": "Gas Siphon I",
                "description": "A basic gas siphon that can extract gas from gas giants and other gas-rich bodies.",
                "strength": 10,
                "requirements": {"crew": 0, "power": 1},
            }
        ],
        "crew": {"required": -1, "capacity": 0},
    },
    "SHIP_SURVEYOR": {
        "type": "SHIP_SURVEYOR",
        "name": "Surveyor Craft",
        "description": "A specialized spacecraft equipped with surveying mounts, designed for detailed surveying of celestial bodies, resource identification, and scientific research.",
        "purchasePrice": 36666,
        "frame": {
            "symbol": "FRAME_DRONE",
            "name": "Drone",
            "description": "A small, unmanned spacecraft used for various tasks, such as surveillance, transportation, or combat.",
            "moduleSlots": 3,
            "mountingPoints": 2,
            "fuelCapacity": 80,
            "quality": 1,
            "requirements": {"power": 1, "crew": -4},
            "condition": 1,
            "integrity": 1,
        },
        "reactor": {
            "symbol": "REACTOR_CHEMICAL_I",
            "name": "Chemical Reactor I",
            "description": "A basic chemical power reactor, used to generate electricity from chemical reactions.",
            "powerOutput": 15,
            "quality": 3,
            "requirements": {"crew": 3},
            "condition": 1,
            "integrity": 1,
        },
        "engine": {
            "symbol": "ENGINE_IMPULSE_DRIVE_I",
            "name": "Impulse Drive I",
            "description": "A basic low-energy propulsion system that generates thrust for interplanetary travel.",
            "speed": 3,
            "quality": 1,
            "requirements": {"power": 1, "crew": 0},
            "condition": 1,
            "integrity": 1,
        },
        "modules": [],
        "mounts": [
            {
                "symbol": "MOUNT_SURVEYOR_I",
                "name": "Surveyor I",
                "description": "A basic survey probe that can be used to gather information about a mineral deposit.",
                "strength": 1,
                "deposits": [
                    "QUARTZ_SAND",
                    "SILICON_CRYSTALS",
                    "PRECIOUS_STONES",
                    "ICE_WATER",
                    "AMMONIA_ICE",
                    "IRON_ORE",
                    "COPPER_ORE",
                    "SILVER_ORE",
                    "ALUMINUM_ORE",
                    "GOLD_ORE",
                    "PLATINUM_ORE",
                ],
                "requirements": {"crew": 1, "power": 1},
            }
        ],
        "crew": {"required": 0, "capacity": 0},
    },
}
