TRAITS_WAYPOINT = {
    "ASH_CLOUDS": {
        "symbol": "ASH_CLOUDS",
        "name": "Ash Clouds",
        "description": "A location filled with a dense cloud of ash and debris. Sometimes difficult to navigate, and may be hazardous to ships and other vessels. Sometimes able to provide shelter or protection from other hazards.",
    },
    "BARREN": {
        "symbol": "BARREN",
        "name": "Barren",
        "description": "A desolate world with little to no vegetation or water, presenting unique challenges for habitation and resource extraction.",
    },
    "BLACK_MARKET": {
        "symbol": "BLACK_MARKET",
        "name": "Black Market",
        "description": "A hidden network of illegal trade, where outlaws and opportunists gather to exchange contraband and forbidden goods.",
    },
    "BREATHABLE_ATMOSPHERE": {
        "symbol": "BREATHABLE_ATMOSPHERE",
        "name": "Breathable Atmosphere",
        "description": "A waypoint with a life-sustaining atmosphere, allowing for easy colonization and the flourishing of diverse ecosystems without the need for advanced life support systems.",
    },
    "BUREAUCRATIC": {
        "symbol": "BUREAUCRATIC",
        "name": "Bureaucratic",
        "description": "A waypoint governed by complex regulations, red tape, and layers of administration, often leading to inefficiencies and frustration.",
    },
    "CANYONS": {
        "symbol": "CANYONS",
        "name": "Canyons",
        "description": "Deep, winding ravines carved into the landscape by natural forces, providing shelter for settlements and hosting diverse ecosystems.",
    },
    "COMMON_METAL_DEPOSITS": {
        "symbol": "COMMON_METAL_DEPOSITS",
        "name": "Common Metal Deposits",
        "description": "A waypoint rich in common metal ores like iron, copper, and aluminum, essential for construction and manufacturing.",
    },
    "CORROSIVE_ATMOSPHERE": {
        "symbol": "CORROSIVE_ATMOSPHERE",
        "name": "Corrosive Atmosphere",
        "description": "A hostile environment with an atmosphere that can rapidly degrade materials and equipment, requiring advanced engineering solutions to ensure the safety and longevity of structures and vehicles.",
    },
    "CORRUPT": {
        "symbol": "CORRUPT",
        "name": "Corrupt",
        "description": "Plagued by underhanded dealings and illicit activities, this waypoint has a reputation for its pervasive criminal element.",
    },
    "CRUSHING_GRAVITY": None,
    "DEBRIS_CLUSTER": {
        "symbol": "DEBRIS_CLUSTER",
        "name": "Debris Cluster",
        "description": "A region filled with hazardous debris and remnants of celestial bodies or man-made objects, requiring advanced navigational capabilities for ships passing through.",
    },
    "DEEP_CRATERS": {
        "symbol": "DEEP_CRATERS",
        "name": "Deep Craters",
        "description": "Marked by deep, expansive craters, potentially formed by ancient meteor impacts. These formations may offer hidden resources but also pose challenges for mobility and construction.",
    },
    "DIVERSE_LIFE": {
        "symbol": "DIVERSE_LIFE",
        "name": "Diverse Life",
        "description": "A waypoint teeming with a wide variety of life forms, providing ample opportunities for scientific research, trade, and even tourism.",
    },
    "DRY_SEABEDS": {
        "symbol": "DRY_SEABEDS",
        "name": "Dry Seabeds",
        "description": "Vast, desolate landscapes that once held oceans, now exposing the remnants of ancient marine life and providing opportunities for the discovery of valuable resources.",
    },
    "EXPLORATION_OUTPOST": {
        "symbol": "EXPLORATION_OUTPOST",
        "name": "Exploration Outpost",
        "description": "A forward-operating base for explorers, scientists, and pioneers, providing support and resources for those venturing into uncharted territories.",
    },
    "EXPLOSIVE_GASES": {
        "symbol": "EXPLOSIVE_GASES",
        "name": "Explosive Gases",
        "description": "A volatile environment filled with highly reactive gases, posing a constant risk to those who venture too close and offering opportunities for harvesting valuable materials such as hydrocarbons.",
    },
    "EXTREME_PRESSURE": {
        "symbol": "EXTREME_PRESSURE",
        "name": "Extreme Pressure",
        "description": "A location characterized by immense atmospheric pressure, demanding robust engineering solutions and innovative approaches for exploration and resource extraction.",
    },
    "EXTREME_TEMPERATURES": {
        "symbol": "EXTREME_TEMPERATURES",
        "name": "Extreme Temperatures",
        "description": "A waypoint with scorching heat or freezing cold, requiring specialized equipment and technology to survive and thrive in these harsh environments.",
    },
    "FOSSILS": {
        "symbol": "FOSSILS",
        "name": "Fossils",
        "description": "A waypoint rich in the remains of ancient life, offering a valuable window into the past and the potential for scientific discovery.",
    },
    "FROZEN": {
        "symbol": "FROZEN",
        "name": "Frozen",
        "description": "An ice-covered world with frigid temperatures, providing unique research opportunities and resources such as ice water, ammonia ice, and other frozen compounds.",
    },
    "HIGH_TECH": {
        "symbol": "HIGH_TECH",
        "name": "High-Tech",
        "description": "A center of innovation and cutting-edge technology, driving progress and attracting skilled individuals from around the galaxy.",
    },
    "HOLLOWED_INTERIOR": {
        "symbol": "HOLLOWED_INTERIOR",
        "name": "Hollowed Interior",
        "description": "A location with large hollow spaces beneath its surface, providing unique opportunities for subterranean construction and resource extraction, but also posing risks of structural instability.",
    },
    "ICE_CRYSTALS": {
        "symbol": "ICE_CRYSTALS",
        "name": "Ice Crystals",
        "description": "Expansive fields of ice, providing a vital source of water and other resources such as ammonia ice, liquid hydrogen, and liquid nitrogen for local populations and industries.",
    },
    "INDUSTRIAL": {
        "symbol": "INDUSTRIAL",
        "name": "Industrial",
        "description": "A waypoint dominated by factories, refineries, and other heavy industries, often accompanied by pollution and a bustling workforce.",
    },
    "JOVIAN": None,
    "JUNGLE": {
        "symbol": "JUNGLE",
        "name": "Jungle",
        "description": "A lush, tropical world with dense vegetation and a thriving ecosystem, offering a wealth of resources and unique opportunities for research and exploration.",
    },
    "MAGMA_SEAS": {
        "symbol": "MAGMA_SEAS",
        "name": "Magma Seas",
        "description": "A waypoint dominated by molten rock and intense heat, creating inhospitable conditions and requiring specialized technology to navigate and harvest resources.",
    },
    "MARKETPLACE": {
        "symbol": "MARKETPLACE",
        "name": "Marketplace",
        "description": "A thriving center of commerce where traders from across the galaxy gather to buy, sell, and exchange goods.",
    },
    "MEGA_STRUCTURES": {
        "symbol": "MEGA_STRUCTURES",
        "name": "Mega Structures",
        "description": "Colossal feats of engineering, these structures house entire cities, industries, or even ecosystems within their vast interiors.",
    },
    "METHANE_POOLS": {
        "symbol": "METHANE_POOLS",
        "name": "Methane Pools",
        "description": "Large reservoirs of methane gas, used for fuel and in various industrial processes such as the production of hydrocarbons.",
    },
    "MICRO_GRAVITY_ANOMALIES": {
        "symbol": "MICRO_GRAVITY_ANOMALIES",
        "name": "Micro-Gravity Anomalies",
        "description": "Unpredictable gravity fields, making navigation and construction particularly challenging. These anomalies may also yield unique scientific research opportunities.",
    },
    "MILITARY_BASE": {
        "symbol": "MILITARY_BASE",
        "name": "Military Base",
        "description": "A fortified stronghold housing armed forces, advanced weaponry, and strategic assets for defense or offense.",
    },
    "MINERAL_DEPOSITS": {
        "symbol": "MINERAL_DEPOSITS",
        "name": "Mineral Deposits",
        "description": "Abundant mineral resources, attracting mining operations and providing valuable materials such as silicon crystals and quartz sand for various industries.",
    },
    "MUTATED_FLORA": {
        "symbol": "MUTATED_FLORA",
        "name": "Mutated Flora",
        "description": "A waypoint teeming with plant life that has undergone dramatic genetic changes, creating a unique and diverse ecosystem with potential for scientific research and discovery.",
    },
    "OCEAN": {
        "symbol": "OCEAN",
        "name": "Ocean",
        "description": "A world dominated by vast, interconnected bodies of water, presenting unique challenges for habitation and resource extraction while supporting a diverse array of marine life.",
    },
    "OUTPOST": {
        "symbol": "OUTPOST",
        "name": "Outpost",
        "description": "A small, remote settlement providing essential services and a safe haven for travelers passing through.",
    },
    "OVERCROWDED": {
        "symbol": "OVERCROWDED",
        "name": "Overcrowded",
        "description": "A waypoint teeming with inhabitants, leading to cramped living conditions and a high demand for resources.",
    },
    "PERPETUAL_DAYLIGHT": {
        "symbol": "PERPETUAL_DAYLIGHT",
        "name": "Perpetual Daylight",
        "description": "A waypoint that never experiences darkness, providing abundant solar energy and unique living conditions for its inhabitants.",
    },
    "PERPETUAL_OVERCAST": {
        "symbol": "PERPETUAL_OVERCAST",
        "name": "Perpetual Overcast",
        "description": "A location with a constant cloud cover, resulting in a perpetually dim and shadowy environment, often impacting local weather and ecosystems.",
    },
    "PIRATE_BASE": {
        "symbol": "PIRATE_BASE",
        "name": "Pirate Base",
        "description": "A hidden stronghold for pirates and other outlaws, providing a safe haven for their illicit activities and a base of operations for raids and other criminal activities. You wouldn't support pirates against your faction, would you?",
    },
    "PRECIOUS_METAL_DEPOSITS": {
        "symbol": "PRECIOUS_METAL_DEPOSITS",
        "name": "Precious Metal Deposits",
        "description": "A source of valuable metals like gold, silver, and platinum, as well as their ores, prized for their rarity, beauty, and various applications.",
    },
    "RADIOACTIVE": {
        "symbol": "RADIOACTIVE",
        "name": "Radioactive",
        "description": "A hazardous location with elevated levels of radiation, requiring specialized equipment and shielding for safe habitation and exploration.",
    },
    "RARE_METAL_DEPOSITS": {
        "symbol": "RARE_METAL_DEPOSITS",
        "name": "Rare Metal Deposits",
        "description": "A treasure trove of scarce metal ores such as uranite and meritium, highly sought after for their unique properties and uses.",
    },
    "RESEARCH_FACILITY": {
        "symbol": "RESEARCH_FACILITY",
        "name": "Research Facility",
        "description": "A state-of-the-art institution dedicated to scientific research and development, often focusing on specific areas of expertise.",
    },
    "ROCKY": {
        "symbol": "ROCKY",
        "name": "Rocky",
        "description": "A world with a rugged, rocky landscape, rich in minerals and other resources, providing a variety of opportunities for mining, research, and exploration.",
    },
    "SALT_FLATS": {
        "symbol": "SALT_FLATS",
        "name": "Salt Flats",
        "description": "Expansive, barren plains covered in a thick layer of salt, offering unique opportunities for resource extraction, scientific research, and other activities.",
    },
    "SCARCE_LIFE": {
        "symbol": "SCARCE_LIFE",
        "name": "Scarce Life",
        "description": "A waypoint with sparse signs of life, often presenting unique challenges for survival and adaptation in a harsh environment.",
    },
    "SCATTERED_SETTLEMENTS": {
        "symbol": "SCATTERED_SETTLEMENTS",
        "name": "Scattered Settlements",
        "description": "A collection of dispersed communities, each independent yet connected through trade and communication networks.",
    },
    "SHALLOW_CRATERS": {
        "symbol": "SHALLOW_CRATERS",
        "name": "Shallow Craters",
        "description": "Numerous shallow craters, offering easier access to sub-surface resources but also creating an uneven terrain that can complicate land-based activities.",
    },
    "SHIPYARD": {
        "symbol": "SHIPYARD",
        "name": "Shipyard",
        "description": "A bustling hub for the construction, repair, and sale of various spacecraft, from humble shuttles to mighty warships.",
    },
    "SPRAWLING_CITIES": {
        "symbol": "SPRAWLING_CITIES",
        "name": "Sprawling Cities",
        "description": "Expansive urban centers that stretch across the landscape, boasting advanced infrastructure and diverse populations.",
    },
    "STRIPPED": {
        "symbol": "STRIPPED",
        "name": "Stripped",
        "description": "A location that has been over-mined or over-harvested, resulting in depleted resources and barren landscapes.",
    },
    "STRONG_GRAVITY": {
        "symbol": "STRONG_GRAVITY",
        "name": "Strong Gravity",
        "description": "A waypoint with a powerful gravitational force, requiring specialized technology and infrastructure to support habitation and resource extraction.",
    },
    "STRONG_MAGNETOSPHERE": {
        "symbol": "STRONG_MAGNETOSPHERE",
        "name": "Strong Magnetosphere",
        "description": "A waypoint enveloped in a powerful magnetic field, potentially affecting spacecraft systems, and creating unique phenomena such as the concentration of exotic matter and graviton emitters.",
    },
    "SUPERVOLCANOES": {
        "symbol": "SUPERVOLCANOES",
        "name": "Supervolcanoes",
        "description": "Gargantuan volcanic structures capable of cataclysmic eruptions, shaping the environment and posing a constant threat to nearby settlements.",
    },
    "SURVEILLANCE_OUTPOST": {
        "symbol": "SURVEILLANCE_OUTPOST",
        "name": "Surveillance Outpost",
        "description": "A covert installation tasked with monitoring and collecting intelligence on nearby regions and potential threats.",
    },
    "SWAMP": {
        "symbol": "SWAMP",
        "name": "Swamp",
        "description": "A damp, murky world characterized by its wetlands and abundant vegetation, fostering a diverse ecosystem and offering potential resources like hydrocarbons and exotic plant life.",
    },
    "TEMPERATE": {
        "symbol": "TEMPERATE",
        "name": "Temperate",
        "description": "A world with a mild climate and balanced ecosystem, providing a comfortable environment for a variety of life forms and supporting diverse industries.",
    },
    "TERRAFORMED": {
        "symbol": "TERRAFORMED",
        "name": "Terraformed",
        "description": "A waypoint that has been artificially transformed to support life, showcasing the engineering prowess of its inhabitants and providing a hospitable environment for colonization.",
    },
    "THIN_ATMOSPHERE": {
        "symbol": "THIN_ATMOSPHERE",
        "name": "Thin Atmosphere",
        "description": "A location with a sparse atmosphere, making it difficult to support life without specialized life-support systems.",
    },
    "TOXIC_ATMOSPHERE": {
        "symbol": "TOXIC_ATMOSPHERE",
        "name": "Toxic Atmosphere",
        "description": "A waypoint with a poisonous atmosphere, necessitating the use of specialized equipment and technology to protect inhabitants and visitors from harmful substances.",
    },
    "TRADING_HUB": {
        "symbol": "TRADING_HUB",
        "name": "Trading Hub",
        "description": "A critical junction in the galaxy's trade network, with countless goods and services flowing through daily.",
    },
    "UNCHARTED": {
        "symbol": "UNCHARTED",
        "name": "Uncharted",
        "description": "An unexplored region of space, full of potential discoveries and hidden dangers.",
    },
    "UNDER_CONSTRUCTION": None,
    "UNSTABLE_COMPOSITION": {
        "symbol": "UNSTABLE_COMPOSITION",
        "name": "Unstable Composition",
        "description": "A location with volatile geological composition, making it prone to frequent seismic activities and necessitating specialized construction techniques for long-term habitation or activity.",
    },
    "VAST_RUINS": {
        "symbol": "VAST_RUINS",
        "name": "Vast Ruins",
        "description": "The remnants of a long-lost civilization, these ancient structures hold secrets waiting to be uncovered and offer a glimpse into the history of the galaxy.",
    },
    "VIBRANT_AURORAS": {
        "symbol": "VIBRANT_AURORAS",
        "name": "Vibrant Auroras",
        "description": "A celestial light show caused by the interaction of charged particles with the waypoint's atmosphere, creating a mesmerizing spectacle and attracting tourists from across the galaxy.",
    },
    "VOLCANIC": {
        "symbol": "VOLCANIC",
        "name": "Volcanic",
        "description": "A volatile world marked by intense volcanic activity, creating a hazardous environment with the potential for valuable resource extraction, such as rare metals and geothermal energy.",
    },
    "WEAK_GRAVITY": {
        "symbol": "WEAK_GRAVITY",
        "name": "Weak Gravity",
        "description": "A waypoint with a low gravitational pull, providing unique opportunities for research and industry while also challenging the adaptation of life forms and technology.",
    },
}
TRAITS_FACTION = {
    "ADAPTABLE": {
        "symbol": "ADAPTABLE",
        "name": "Adaptable",
        "description": "Quick to adapt to changing circumstances, with the ability to adjust their plans or strategies in response to new information or challenges. Sometimes able to thrive in a wide range of environments or situations, but may also be vulnerable to sudden or unexpected changes.",
    },
    "AGGRESSIVE": {
        "symbol": "AGGRESSIVE",
        "name": "Aggressive",
        "description": "Quick to engage in conflict or aggression, often without provocation. Sometimes unpredictable and difficult to negotiate with, and may prioritize their own interests over the needs of others.",
    },
    "BOLD": {
        "symbol": "BOLD",
        "name": "Bold",
        "description": "Unafraid to take risks and challenge the status quo. Sometimes willing to do things that others would not dare, and may be able to overcome obstacles and challenges that would be insurmountable for others. Sometimes able to inspire and motivate others to take bold action as well.",
    },
    "BRUTAL": {
        "symbol": "BRUTAL",
        "name": "Brutal",
        "description": "Fierce and ruthless, with a willingness to use violence or intimidation to achieve their goals. Often feared or respected by others, but may also be viewed as a threat or enemy by those who oppose their methods.",
    },
    "BUREAUCRATIC": None,
    "CAPITALISTIC": None,
    "CLAN": None,
    "COLLABORATIVE": {
        "symbol": "COLLABORATIVE",
        "name": "Collaborative",
        "description": "Known for their ability to work well with others. Sometimes willing to share resources, knowledge, and expertise in order to achieve common goals. Often have a strong sense of community and cooperation, and may prioritize the needs of the group over those of the individual.",
    },
    "COMMERCIAL": {
        "symbol": "COMMERCIAL",
        "name": "Commercial",
        "description": "Focused on trade and commerce, with a strong emphasis on economic growth and development. Sometimes willing to engage in a wide range of activities in order to promote trade and facilitate the exchange of goods and resources.",
    },
    "COOPERATIVE": {
        "symbol": "COOPERATIVE",
        "name": "Cooperative",
        "description": "Willing to work together with others in order to achieve common goals. Sometimes able to coordinate and cooperate effectively, using their collective strengths and resources to overcome challenges and achieve success. Often prioritize collaboration and teamwork over individual achievement.",
    },
    "CURIOUS": {
        "symbol": "CURIOUS",
        "name": "Curious",
        "description": "Possessing a strong desire to learn and explore. Sometimes interested in a wide range of topics and may be willing to take risks in order to satisfy their curiosity. Sometimes able to think outside the box and come up with creative solutions to challenges.",
    },
    "DARING": {
        "symbol": "DARING",
        "name": "Daring",
        "description": "Willing to take risks and challenges. Sometimes unafraid to explore new and unknown territories, and may be willing to take bold and decisive action in order to achieve their goals. Sometimes able to overcome challenges that would be insurmountable for others.",
    },
    "DEFENSIVE": {
        "symbol": "DEFENSIVE",
        "name": "Defensive",
        "description": "Prepared and able to defend themselves against potential threats. Often have strong military forces or defensive capabilities, but may also be vulnerable to surprise attacks or other forms of aggression.",
    },
    "DEXTEROUS": {
        "symbol": "DEXTEROUS",
        "name": "Dexterous",
        "description": "Skilled in the use of their hands and able to perform complex tasks with precision and accuracy. Known for their manual dexterity and ability to manipulate objects with ease, making them valuable in a wide range of tasks and activities.",
    },
    "DISTRUSTFUL": None,
    "DIVERSE": {
        "symbol": "DIVERSE",
        "name": "Diverse",
        "description": "Comprised of a diverse range of individuals, cultures, or beliefs. Sometimes able to offer a wide range of perspectives and expertise, but may also face challenges in achieving unity or consensus.",
    },
    "DOMINANT": None,
    "DOMINION": None,
    "ENTREPRENEURIAL": None,
    "ESTABLISHED": None,
    "EXILES": None,
    "EXPLORATORY": {
        "symbol": "EXPLORATORY",
        "name": "Exploratory",
        "description": "Dedicated to exploration and discovery. Sometimes interested in mapping new territories and uncovering the secrets of the universe. Sometimes able to overcome obstacles and challenges in order to advance the boundaries of human knowledge and understanding.",
    },
    "FLEETING": {
        "symbol": "FLEETING",
        "name": "Fleeting",
        "description": "Not permanently settled in one place, with a tendency to move frequently or unpredictably. Sometimes difficult to find or track, but may also be able to take advantage of opportunities or evade threats by moving quickly or unexpectedly.",
    },
    "FLEXIBLE": {
        "symbol": "FLEXIBLE",
        "name": "Flexible",
        "description": "Able to adapt to changing circumstances and environments. Sometimes able to quickly switch between different strategies and tactics in order to respond to new challenges or opportunities. Sometimes able to improvise and think on their feet, making them difficult to predict or outmaneuver.",
    },
    "FORSAKEN": None,
    "FRAGMENTED": None,
    "FREE_MARKETS": None,
    "FRINGE": None,
    "GUILD": None,
    "IMPERIALISTIC": {
        "symbol": "IMPERIALISTIC",
        "name": "Imperialistic",
        "description": "Dedicated to expanding their territory and influence. Often seek to conquer or subjugate other factions, and may have a hierarchical and authoritarian structure. Often prioritize the interests of their own faction over the needs of others.",
    },
    "INDEPENDENT": None,
    "INDUSTRIOUS": {
        "symbol": "INDUSTRIOUS",
        "name": "Industrious",
        "description": "Known for their hard work and dedication. Highly productive and efficient, with a focus on maximizing their output. Sometimes able to produce large quantities of goods or resources, but may also be vulnerable to exploitation or overwork.",
    },
    "INESCAPABLE": None,
    "INNOVATIVE": {
        "symbol": "INNOVATIVE",
        "name": "Innovative",
        "description": "Willing to try new and untested ideas. Sometimes able to come up with creative and original solutions to problems, and may be able to think outside the box. Sometimes at the forefront of technological or social change, and may be willing to take risks in order to advance the boundaries of human knowledge and understanding.",
    },
    "INTELLIGENT": {
        "symbol": "INTELLIGENT",
        "name": "Intelligent",
        "description": "Possessing a high level of intelligence and analytical ability. Sometimes skilled in a wide range of fields, including science, technology, and engineering. Often have a strong curiosity and a desire to understand the mysteries of the universe.",
    },
    "ISOLATED": None,
    "LOCALIZED": None,
    "MILITARISTIC": {
        "symbol": "MILITARISTIC",
        "name": "Militaristic",
        "description": "Focused on building and maintaining a strong military force. Often prioritize military power and readiness over other concerns, and may be quick to engage in conflict or aggression in order to achieve their goals.",
    },
    "NOTABLE": None,
    "PEACEFUL": {
        "symbol": "PEACEFUL",
        "name": "Peaceful",
        "description": "Dedicated to maintaining peace and harmony. Sometimes reluctant to engage in conflict, and may prefer to resolve disputes through negotiation and compromise. Sometimes able to provide sanctuary or aid to those in need, but may also be vulnerable to aggression from other factions.",
    },
    "PIRATES": None,
    "PROGRESSIVE": {
        "symbol": "PROGRESSIVE",
        "name": "Progressive",
        "description": "Open to new ideas and change. Sometimes willing to embrace new technologies and ways of thinking, and may prioritize the advancement of knowledge and understanding over tradition and established ways of doing things.",
    },
    "PROUD": {
        "symbol": "PROUD",
        "name": "Proud",
        "description": "Proud of their heritage, culture, or achievements, with a strong sense of identity and self-respect. Sometimes resistant to change or outside influence, and may be willing to defend their beliefs or values against challenges or threats.",
    },
    "RAIDERS": None,
    "REBELLIOUS": None,
    "RESEARCH_FOCUSED": {
        "symbol": "RESEARCH_FOCUSED",
        "name": "Research-Focused",
        "description": "Dedicated to advancing knowledge and understanding through research and experimentation. Often have a strong focus on scientific and technological development, and may be willing to take risks and explore new ideas in order to make progress.",
    },
    "RESOURCEFUL": {
        "symbol": "RESOURCEFUL",
        "name": "Resourceful",
        "description": "Known for their ingenuity and ability to make the most out of limited resources. Able to improvise and adapt to changing circumstances, using whatever is available to them in order to overcome challenges and achieve their goals.",
    },
    "SCAVENGERS": {
        "symbol": "SCAVENGERS",
        "name": "Scavengers",
        "description": "Skilled at finding and salvaging valuable resources and materials from abandoned or derelict ships, space stations, and other structures. Resourceful and able to make the most out of what others have left behind.",
    },
    "SECRETIVE": {
        "symbol": "SECRETIVE",
        "name": "Secretive",
        "description": "Guarded and secretive, with a tendency to keep their plans and activities hidden from others. Sometimes difficult to negotiate with or trust, but often have valuable information or resources that they are willing to share with the right partners.",
    },
    "SELF_INTERESTED": None,
    "SELF_SUFFICIENT": {
        "symbol": "SELF_SUFFICIENT",
        "name": "Self-Sufficient",
        "description": "Able to sustain themselves without relying on others for support or resources. Sometimes independent and self-reliant, but may also be isolated or vulnerable to external threats.",
    },
    "SMUGGLERS": {
        "symbol": "SMUGGLERS",
        "name": "Smugglers",
        "description": "Skilled at moving goods or people across borders or through restricted areas. Sometimes able to avoid detection or interception, and may be able to find hidden or secret routes. Sometimes able to evade or bypass regulations or controls, and may be willing to engage in illegal or risky activities in order to achieve their goals.",
    },
    "STRATEGIC": {
        "symbol": "STRATEGIC",
        "name": "Strategic",
        "description": "Skilled in the art of strategy and planning. Sometimes able to think ahead and anticipate the actions of others, and may be able to develop effective plans to achieve their goals. Sometimes able to make calculated risks and sacrifices in order to gain a strategic advantage.",
    },
    "TECHNOLOGICALLY_ADVANCED": None,
    "TREASURE_HUNTERS": {
        "symbol": "TREASURE_HUNTERS",
        "name": "Treasure Hunters",
        "description": "Always on the lookout for valuable artifacts, ancient relics, and other rare and valuable items. Curious and willing to take risks in order to uncover hidden treasures and secrets of the universe.",
    },
    "UNITED": {
        "symbol": "UNITED",
        "name": "United",
        "description": "Strongly united and cohesive, often with a strong sense of shared identity and purpose. Sometimes able to work together effectively and efficiently, and may be difficult to divide or conquer. Sometimes able to overcome challenges that would be insurmountable for a less united group.",
    },
    "UNPREDICTABLE": {
        "symbol": "UNPREDICTABLE",
        "name": "Unpredictable",
        "description": "Difficult to predict or anticipate, with a tendency to act in unexpected or chaotic ways.",
    },
    "VISIONARY": {
        "symbol": "VISIONARY",
        "name": "Visionary",
        "description": "Possessing a clear and compelling vision for the future. Sometimes able to see beyond the present and anticipate the needs and challenges of tomorrow. Sometimes able to inspire and guide others towards a better and brighter future, and may be willing to take bold and decisive action to make their vision a reality.",
    },
    "WELCOMING": {
        "symbol": "WELCOMING",
        "name": "Welcoming",
        "description": "Friendly and hospitable, with a tendency to be open and welcoming to outsiders. Sometimes a valuable source of information and resources for travelers and traders, but may also be vulnerable to exploitation or manipulation by more powerful factions.",
    },
}
