name: st2
channels:
  - conda-forge
dependencies:
  - conda-ecosystem-user-package-isolation
  - python  >=3.10

  - bokeh
  - graphviz
  - loguru
  - matplotlib-base
  - networkx
  - numpy
  - pandas
  - postgresql
  - psycopg
  - python-dotenv
  - requests-ratelimiter
  - seaborn
  - scipy
  - scikit-learn
  - xdg

  # dev
  - black
  - isort
  - pydeps
  - pytest
